<?php
/**
 * Created by PhpStorm.
 * User: tungphung
 * Date: 3/3/17
 * Time: 9:22 AM
 */

namespace api\models;

use Yii;

class UserToken extends \common\models\UserToken
{
    public function  fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function extraFields()
    {
        $new = ['user'];
        $fields = array_merge(parent::fields(), $new);
        return $fields;
    }

}